// GENERATED from Business Health Measurement Framework UMKM v0.2 (Audit).
// Source of truth. Jangan mengubah teks, bobot, atau trigger tanpa menaikkan versi.
import type { CriticalFlagDef, CrossDimensionRule, DimensionDef, HealthStatusRule, IndicatorDef } from "@/types/assessment";

export const QUESTIONNAIRE_VERSION = "0.2";
export const SCORING_VERSION = "0.2";
export const MAX_RAW_SCORE = 4;

export const DIMENSIONS: DimensionDef[] = [
  { id: "FIN", code: "FIN", name: "Kesehatan Keuangan", shortName: "Keuangan", weight: 0.2, purpose: "Menilai apakah usaha memahami kondisi keuangannya, menghasilkan laba, memiliki arus kas memadai, dan mampu memenuhi kewajiban.", scope: "Pencatatan, pemisahan uang, HPP, profitabilitas, arus kas, ketahanan kas" },
  { id: "SAL", code: "SAL", name: "Kesehatan Penjualan", shortName: "Penjualan", weight: 0.15, purpose: "Menilai kemampuan usaha menghasilkan transaksi secara konsisten dan mempertahankan/meningkatkan penjualan.", scope: "Tren penjualan, target, sumber pendapatan, kanal penjualan" },
  { id: "CUS", code: "CUS", name: "Kesehatan Pelanggan", shortName: "Pelanggan", weight: 0.15, purpose: "Menilai kualitas basis pelanggan: pemahaman pelanggan, repeat purchase, database, dan feedback.", scope: "Pemahaman pelanggan, retensi, database, kepuasan/feedback" },
  { id: "PRO", code: "PRO", name: "Kesehatan Produk & Value Proposition", shortName: "Produk", weight: 0.15, purpose: "Menilai apakah produk relevan bagi pasar, berbeda, konsisten, dan memiliki struktur harga yang sehat.", scope: "Value proposition, kualitas, produk unggulan, harga/margin" },
  { id: "MKT", code: "MKT", name: "Kesehatan Pemasaran", shortName: "Pemasaran", weight: 0.1, purpose: "Menilai apakah aktivitas pemasaran menjangkau target yang tepat dan berkontribusi terhadap prospek serta transaksi.", scope: "Target market, kanal, konsistensi, pengukuran hasil" },
  { id: "OPS", code: "OPS", name: "Kesehatan Operasional", shortName: "Operasional", weight: 0.15, purpose: "Menilai kemampuan usaha memenuhi pesanan dengan kualitas konsisten, proses efisien, dan ketergantungan owner yang terkendali.", scope: "SOP, kapasitas, persediaan/supplier, quality/fulfillment, owner dependency" },
  { id: "GRW", code: "GRW", name: "Kesiapan Bertumbuh & Ketahanan", shortName: "Pertumbuhan", weight: 0.1, purpose: "Menilai kesiapan usaha untuk tumbuh dan bertahan melalui arah bisnis, legalitas, tim/sistem, serta mitigasi risiko.", scope: "Target & rencana, legalitas, tim/digital/data, resilience" },
];

export const INDICATORS: IndicatorDef[] = [
  {
    id: "FIN-01",
    dimensionId: "FIN",
    subdimension: "Pencatatan Keuangan",
    name: "Kedisiplinan pencatatan transaksi",
    weightInDimension: 20,
    question: "Dalam 1 bulan terakhir, bagaimana Anda mencatat uang masuk dan uang keluar usaha?",
    helperText: "Contoh transaksi: pembelian bahan, penjualan harian, bayar listrik, ongkos kirim.",
    answerType: "single_choice",
    options: [
      { id: "FIN-01-0", label: "Tidak dicatat sama sekali", score: 0, semanticValue: "level_0" },
      { id: "FIN-01-1", label: "Hanya mencatat sesekali atau transaksi besar", score: 1, semanticValue: "level_1" },
      { id: "FIN-01-2", label: "Sebagian besar transaksi sudah dicatat", score: 2, semanticValue: "level_2" },
      { id: "FIN-01-3", label: "Semua transaksi dicatat rutin", score: 3, semanticValue: "level_3" },
      { id: "FIN-01-4", label: "Dicatat rutin dan dibuat rekap untuk melihat kondisi usaha", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Informasi keuangan usaha tidak memadai sehingga pemilik sulit mengetahui kondisi usaha yang sebenarnya.",
    recommendation: "Mulai pencatatan harian pemasukan/pengeluaran; buat rekap mingguan dan bulanan.",
    urgency: 4,
    actionability: 5,
    actionSteps: [
      "Siapkan satu buku atau catatan di HP khusus uang usaha, lalu catat setiap uang masuk dan keluar selama 7 hari tanpa terlewat.",
      "Lanjutkan mencatat setiap hari dan buat rekap sederhana di akhir minggu: total masuk, total keluar, sisa.",
      "Bandingkan rekap dua minggu terakhir dan tandai pengeluaran terbesar.",
      "Buat rekap bulanan dan tentukan satu pengeluaran yang akan dikurangi bulan depan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "FIN-02",
    dimensionId: "FIN",
    subdimension: "Pemisahan Keuangan",
    name: "Pemisahan uang pribadi dan usaha",
    weightInDimension: 15,
    question: "Apakah uang usaha dan uang untuk kebutuhan pribadi sudah dipisahkan?",
    helperText: "Maksudnya uang untuk belanja usaha tidak bercampur dengan uang belanja rumah tangga.",
    answerType: "single_choice",
    options: [
      { id: "FIN-02-0", label: "Masih tercampur sepenuhnya", score: 0, semanticValue: "level_0" },
      { id: "FIN-02-1", label: "Sering masih tercampur", score: 1, semanticValue: "level_1" },
      { id: "FIN-02-2", label: "Sudah mulai dipisahkan, tapi belum konsisten", score: 2, semanticValue: "level_2" },
      { id: "FIN-02-3", label: "Sudah dipisahkan dengan kas/rekening usaha", score: 3, semanticValue: "level_3" },
      { id: "FIN-02-4", label: "Sudah dipisahkan dan setiap pengambilan untuk kebutuhan pribadi juga dicatat", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Uang usaha dan pribadi bercampur sehingga kas bisnis dan laba sulit dinilai secara akurat.",
    recommendation: "Pisahkan kas/rekening usaha dan tetapkan mekanisme pengambilan uang pribadi.",
    urgency: 3,
    actionability: 5,
    actionSteps: [
      "Buat satu tempat atau rekening khusus uang usaha dan pindahkan uang usaha yang masih tercampur ke sana.",
      "Selama 7 hari, semua belanja usaha diambil hanya dari tempat/rekening usaha.",
      "Tetapkan jumlah tetap yang Anda ambil untuk kebutuhan pribadi setiap minggu dan catat pengambilannya.",
      "Cek catatan sebulan: pastikan tidak ada belanja pribadi yang keluar dari uang usaha.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "FIN-03",
    dimensionId: "FIN",
    subdimension: "HPP & Harga Pokok",
    name: "Pemahaman HPP produk/jasa",
    weightInDimension: 20,
    question: "Apakah Anda sudah menghitung biaya untuk membuat atau mendapatkan satu produk/jasa utama (HPP)?",
    helperText: "Hitungan biaya termasuk bahan, kemasan, ongkos produksi, dan upah yang langsung terpakai.",
    answerType: "single_choice",
    options: [
      { id: "FIN-03-0", label: "Belum tahu cara menghitungnya", score: 0, semanticValue: "level_0" },
      { id: "FIN-03-1", label: "Hanya memperkirakan", score: 1, semanticValue: "level_1" },
      { id: "FIN-03-2", label: "Pernah menghitung, tetapi sudah lama tidak diperbarui", score: 2, semanticValue: "level_2" },
      { id: "FIN-03-3", label: "Dihitung dan diperbarui saat biaya berubah", score: 3, semanticValue: "level_3" },
      { id: "FIN-03-4", label: "Dihitung rutin dan dipakai untuk menentukan harga jual", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Harga jual berisiko tidak menutup biaya karena HPP belum diketahui secara memadai.",
    recommendation: "Hitung ulang HPP produk utama, masukkan bahan, tenaga langsung, kemasan, dan biaya relevan.",
    urgency: 4,
    actionability: 4,
    actionSteps: [
      "Pilih 3 produk/jasa paling laku, lalu tulis semua bahan dan kemasannya beserta harganya.",
      "Tambahkan ongkos produksi dan upah yang langsung terpakai untuk tiap produk, lalu hitung biaya per satuan.",
      "Bandingkan biaya per satuan dengan harga jual sekarang dan tandai produk yang untungnya tipis.",
      "Tetapkan harga baru atau turunkan biaya untuk produk yang untungnya tipis.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "FIN-04",
    dimensionId: "FIN",
    subdimension: "Profitabilitas",
    name: "Pengetahuan laba bersih",
    weightInDimension: 20,
    question: "Setiap akhir bulan, apakah Anda tahu usaha Anda untung atau rugi setelah semua biaya dibayar?",
    helperText: "Untung/rugi dihitung setelah semua biaya dibayar: bahan, listrik, sewa, upah, ongkir, dan lainnya.",
    answerType: "single_choice",
    options: [
      { id: "FIN-04-0", label: "Tidak tahu", score: 0, semanticValue: "level_0" },
      { id: "FIN-04-1", label: "Hanya kira-kira", score: 1, semanticValue: "level_1" },
      { id: "FIN-04-2", label: "Kadang menghitung", score: 2, semanticValue: "level_2" },
      { id: "FIN-04-3", label: "Menghitung setiap bulan", score: 3, semanticValue: "level_3" },
      { id: "FIN-04-4", label: "Menghitung setiap bulan dan memakai hasilnya untuk mengambil keputusan", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha belum mampu memastikan apakah penjualan menghasilkan keuntungan yang cukup.",
    recommendation: "Susun laporan laba-rugi sederhana bulanan dan pantau gross margin serta net margin.",
    urgency: 4,
    actionability: 4,
    actionSteps: [
      "Kumpulkan catatan uang masuk dan keluar bulan lalu dalam satu daftar.",
      "Hitung: total uang masuk dikurangi total biaya, dan tulis hasilnya untung atau rugi.",
      "Kelompokkan biaya menjadi bahan, tenaga, dan biaya tetap agar terlihat yang paling besar.",
      "Ulangi perhitungan untuk bulan berjalan dan bandingkan dengan bulan sebelumnya.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "FIN-05",
    dimensionId: "FIN",
    subdimension: "Arus Kas",
    name: "Kemampuan kas memenuhi biaya rutin",
    weightInDimension: 15,
    question: "Dalam 3 bulan terakhir, apakah uang usaha biasanya cukup untuk membayar biaya rutin tepat waktu?",
    helperText: "Biaya rutin contohnya bahan, listrik, upah, sewa, dan cicilan.",
    answerType: "single_choice",
    options: [
      { id: "FIN-05-0", label: "Hampir selalu tidak cukup", score: 0, semanticValue: "level_0" },
      { id: "FIN-05-1", label: "Sering tidak cukup", score: 1, semanticValue: "level_1" },
      { id: "FIN-05-2", label: "Kadang tidak cukup", score: 2, semanticValue: "level_2" },
      { id: "FIN-05-3", label: "Biasanya cukup", score: 3, semanticValue: "level_3" },
      { id: "FIN-05-4", label: "Selalu cukup dan kebutuhan kas sudah direncanakan", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha mengalami tekanan arus kas yang dapat mengganggu operasional meskipun memiliki penjualan.",
    recommendation: "Buat proyeksi kas 4–8 minggu; percepat penagihan dan kendalikan pengeluaran non-prioritas.",
    urgency: 5,
    actionability: 3,
    actionSteps: [
      "Tulis daftar biaya rutin usaha 4 minggu ke depan beserta tanggal jatuh temponya.",
      "Perkirakan uang masuk mingguan dan tandai minggu yang diperkirakan kurang.",
      "Tagih pembayaran yang tertunda dan tunda pengeluaran yang bukan prioritas pada minggu yang kurang.",
      "Perbarui daftar biaya dan perkiraan uang masuk untuk 4 minggu berikutnya.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "FIN-06",
    dimensionId: "FIN",
    subdimension: "Ketahanan Kas & Kewajiban",
    name: "Cadangan kas dan kemampuan membayar kewajiban",
    weightInDimension: 10,
    question: "Kalau mulai hari ini tidak ada pemasukan baru, kira-kira uang usaha yang tersedia bisa membayar biaya rutin berapa lama?",
    helperText: "Perkirakan berapa lama uang yang ada sekarang bisa menutup biaya rutin usaha.",
    answerType: "single_choice",
    options: [
      { id: "FIN-06-0", label: "Belum tahu", score: 0, semanticValue: "unknown" },
      { id: "FIN-06-1", label: "Kurang dari 2 minggu", score: 1, semanticValue: "less_than_2_weeks" },
      { id: "FIN-06-2", label: "Sekitar 2–4 minggu", score: 2, semanticValue: "2_to_4_weeks" },
      { id: "FIN-06-3", label: "Sekitar 1–2 bulan", score: 3, semanticValue: "1_to_2_months" },
      { id: "FIN-06-4", label: "Lebih dari 2 bulan", score: 4, semanticValue: "more_than_2_months" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Cadangan kas sangat tipis atau tidak diketahui, sehingga usaha rentan terhadap gangguan penjualan.",
    recommendation: "Bangun cadangan kas bertahap dan buat daftar jatuh tempo utang/kewajiban.",
    urgency: 5,
    actionability: 4,
    actionSteps: [
      "Hitung sisa uang usaha hari ini dan total biaya rutin per minggu.",
      "Bagi sisa uang dengan biaya mingguan untuk tahu usaha bisa bertahan berapa minggu, lalu catat angkanya.",
      "Sisihkan sejumlah kecil uang usaha setiap kali ada penjualan sebagai cadangan.",
      "Cek kembali cadangan kas dan tetapkan target cadangan minimal 4 minggu biaya rutin.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "SAL-01",
    dimensionId: "SAL",
    subdimension: "Tren Penjualan",
    name: "Perkembangan omzet/transaksi 3 bulan",
    weightInDimension: 30,
    question: "Jika dibandingkan dengan 3 bulan sebelumnya, bagaimana penjualan usaha Anda selama 3 bulan terakhir?",
    helperText: "Bandingkan kira-kira jumlah penjualan 3 bulan terakhir dengan 3 bulan sebelumnya.",
    answerType: "single_choice",
    options: [
      { id: "SAL-01-0", label: "Turun banyak", score: 0, semanticValue: "level_0" },
      { id: "SAL-01-1", label: "Turun sedikit", score: 1, semanticValue: "level_1" },
      { id: "SAL-01-2", label: "Kurang lebih sama", score: 2, semanticValue: "level_2" },
      { id: "SAL-01-3", label: "Naik", score: 3, semanticValue: "level_3" },
      { id: "SAL-01-4", label: "Naik secara konsisten", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Penjualan mengalami penurunan signifikan dan membutuhkan pemeriksaan penyebab segera.",
    recommendation: "Bandingkan penjualan per produk, pelanggan, dan kanal; identifikasi sumber penurunan terbesar.",
    urgency: 5,
    actionability: 3,
    actionSteps: [
      "Tulis jumlah penjualan tiap bulan selama 6 bulan terakhir dari catatan atau perkiraan terbaik.",
      "Bandingkan produk dan pelanggan yang penjualannya turun paling banyak.",
      "Hubungi 5 pelanggan lama yang sudah lama tidak membeli dan tanyakan alasannya.",
      "Jalankan satu penawaran untuk produk yang paling turun dan catat hasilnya.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "SAL-02",
    dimensionId: "SAL",
    subdimension: "Target & Monitoring",
    name: "Penggunaan target penjualan",
    weightInDimension: 20,
    question: "Apakah usaha Anda punya target penjualan bulanan dan mengecek hasilnya?",
    helperText: "Contoh target: jumlah omzet per bulan atau jumlah pesanan per bulan.",
    answerType: "single_choice",
    options: [
      { id: "SAL-02-0", label: "Tidak punya target", score: 0, semanticValue: "level_0" },
      { id: "SAL-02-1", label: "Hanya punya keinginan di pikiran", score: 1, semanticValue: "level_1" },
      { id: "SAL-02-2", label: "Punya target angka", score: 2, semanticValue: "level_2" },
      { id: "SAL-02-3", label: "Target dicatat dan dibandingkan dengan hasil", score: 3, semanticValue: "level_3" },
      { id: "SAL-02-4", label: "Hasil target rutin dicek lalu strategi diperbaiki", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Penjualan belum dikelola dengan target dan evaluasi yang cukup jelas.",
    recommendation: "Tetapkan target omzet/transaksi bulanan dan lakukan review realisasi minimal tiap bulan.",
    urgency: 3,
    actionability: 5,
    actionSteps: [
      "Tetapkan target penjualan bulan ini dalam angka: jumlah omzet atau jumlah pesanan.",
      "Bagi target bulanan menjadi target mingguan dan tulis di tempat yang terlihat.",
      "Catat hasil penjualan setiap minggu dan bandingkan dengan target.",
      "Evaluasi akhir bulan: tulis satu hal yang akan diubah agar target tercapai bulan depan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "SAL-03",
    dimensionId: "SAL",
    subdimension: "Struktur Pendapatan",
    name: "Pengetahuan produk/pelanggan penyumbang penjualan",
    weightInDimension: 25,
    question: "Apakah Anda tahu produk/jasa mana yang paling besar menyumbang penjualan?",
    helperText: "Maksudnya produk atau jasa yang paling banyak menghasilkan uang masuk.",
    answerType: "single_choice",
    options: [
      { id: "SAL-03-0", label: "Tidak tahu", score: 0, semanticValue: "level_0" },
      { id: "SAL-03-1", label: "Hanya berdasarkan perkiraan", score: 1, semanticValue: "level_1" },
      { id: "SAL-03-2", label: "Tahu produk yang paling laku", score: 2, semanticValue: "level_2" },
      { id: "SAL-03-3", label: "Penjualan per produk/jasa dicatat", score: 3, semanticValue: "level_3" },
      { id: "SAL-03-4", label: "Data tersebut dipakai menentukan produk yang difokuskan", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha tidak mengetahui sumber pendapatan utamanya sehingga keputusan produk berisiko salah arah.",
    recommendation: "Kelompokkan penjualan per produk/layanan dan hitung kontribusinya terhadap omzet dan margin.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Catat penjualan per produk/jasa selama 7 hari.",
      "Jumlahkan hasil 2 minggu dan urutkan produk dari yang paling besar menyumbang penjualan.",
      "Bandingkan produk penyumbang terbesar dengan biaya pembuatannya.",
      "Tentukan 3 produk yang akan difokuskan bulan depan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "SAL-04",
    dimensionId: "SAL",
    subdimension: "Kanal Penjualan",
    name: "Kesehatan dan diversifikasi kanal",
    weightInDimension: 25,
    question: "Apakah Anda tahu penjualan paling banyak datang dari mana?",
    helperText: "Contoh sumber penjualan: toko, WhatsApp, Instagram, marketplace, reseller, pelanggan lama.",
    answerType: "single_choice",
    options: [
      { id: "SAL-04-0", label: "Tidak tahu", score: 0, semanticValue: "level_0" },
      { id: "SAL-04-1", label: "Hanya mengandalkan satu tempat/cara dan tidak mengecek hasilnya", score: 1, semanticValue: "level_1" },
      { id: "SAL-04-2", label: "Menggunakan beberapa tempat/cara tetapi hasilnya tidak dicatat", score: 2, semanticValue: "level_2" },
      { id: "SAL-04-3", label: "Penjualan dari tiap sumber dicatat", score: 3, semanticValue: "level_3" },
      { id: "SAL-04-4", label: "Data sumber penjualan dipakai menentukan fokus", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha belum memiliki kanal penjualan yang dapat diandalkan atau tidak memahami sumber transaksinya.",
    recommendation: "Catat sumber setiap transaksi dan prioritaskan 1–2 kanal dengan kontribusi terbaik.",
    urgency: 3,
    actionability: 5,
    actionSteps: [
      "Selama 7 hari, tanyakan setiap pembeli mengetahui usaha Anda dari mana dan catat jawabannya.",
      "Lanjutkan pencatatan dan kelompokkan sumber penjualan (toko, WhatsApp, media sosial, marketplace, reseller).",
      "Hitung jumlah pembeli dari tiap sumber selama 2 minggu.",
      "Pilih 2 sumber terbaik dan tambah aktivitas di sana bulan depan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "CUS-01",
    dimensionId: "CUS",
    subdimension: "Pemahaman Pelanggan",
    name: "Kejelasan pelanggan utama",
    weightInDimension: 25,
    question: "Apakah Anda tahu siapa pelanggan yang paling sering membeli produk/jasa Anda?",
    helperText: "Contoh: ibu rumah tangga sekitar, karyawan kantor, pemilik warung, panitia acara.",
    answerType: "single_choice",
    options: [
      { id: "CUS-01-0", label: "Tidak tahu", score: 0, semanticValue: "level_0" },
      { id: "CUS-01-1", label: "Hanya kira-kira", score: 1, semanticValue: "level_1" },
      { id: "CUS-01-2", label: "Tahu kelompok pelanggan secara umum", score: 2, semanticValue: "level_2" },
      { id: "CUS-01-3", label: "Tahu kelompok pelanggan dan kebutuhan utamanya", score: 3, semanticValue: "level_3" },
      { id: "CUS-01-4", label: "Informasi pelanggan dipakai untuk menentukan produk, layanan, atau promosi", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha belum jelas siapa pelanggan yang dilayani dan masalah apa yang paling penting bagi mereka.",
    recommendation: "Identifikasi 1–3 segmen pelanggan utama dan dokumentasikan kebutuhan serta alasan membeli.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Tulis 20 pembeli terakhir beserta perkiraan usia, pekerjaan, dan lokasi mereka.",
      "Kelompokkan pembeli tersebut menjadi 2–3 kelompok yang paling sering membeli.",
      "Tanyakan pada 5 pelanggan dari kelompok terbesar apa kebutuhan utama mereka.",
      "Tulis satu kalimat siapa pelanggan utama Anda dan gunakan untuk isi promosi.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "CUS-02",
    dimensionId: "CUS",
    subdimension: "Retensi",
    name: "Repeat purchase/pelanggan kembali",
    weightInDimension: 30,
    question: "Apakah pelanggan yang sudah pernah membeli biasanya kembali membeli atau memakai jasa Anda?",
    helperText: "Maksudnya pembeli yang sama membeli lagi di lain waktu.",
    answerType: "single_choice",
    options: [
      { id: "CUS-02-0", label: "Belum tahu karena tidak dicatat", score: 0, semanticValue: "level_0" },
      { id: "CUS-02-1", label: "Hampir tidak pernah", score: 1, semanticValue: "level_1" },
      { id: "CUS-02-2", label: "Kadang-kadang", score: 2, semanticValue: "level_2" },
      { id: "CUS-02-3", label: "Cukup sering", score: 3, semanticValue: "level_3" },
      { id: "CUS-02-4", label: "Sebagian besar pelanggan kembali membeli/menggunakan jasa", score: 4, semanticValue: "level_4" },
    ],
    applicabilityRule: { all: [{ field: "profile.repeatPurchaseApplicable", operator: "equals", value: true }] },
    notApplicableReason: "Tidak relevan untuk model usaha Anda berdasarkan profil yang diisi.",
    allowUserNotApplicable: true,
    diagnosisWhenLow: "Repeat purchase rendah; bisnis terlalu bergantung pada pelanggan baru.",
    recommendation: "Identifikasi pelanggan lama, buat follow-up pascapembelian, dan uji program repeat order.",
    urgency: 4,
    actionability: 4,
    actionSteps: [
      "Buat daftar pelanggan yang pernah membeli 1 bulan terakhir beserta tanggal belinya.",
      "Hubungi 10 pelanggan lama untuk menanyakan kepuasan dan menawarkan pembelian berikutnya.",
      "Catat berapa yang membeli lagi setelah dihubungi.",
      "Tetapkan kebiasaan menghubungi kembali pelanggan setiap selesai satu siklus pembelian.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "CUS-03",
    dimensionId: "CUS",
    subdimension: "Database Pelanggan",
    name: "Kualitas database dan riwayat pelanggan",
    weightInDimension: 20,
    question: "Apakah Anda menyimpan data pelanggan seperti nama, nomor WhatsApp, dan riwayat belanja?",
    helperText: "Contoh: buku catatan atau file berisi nama, nomor WhatsApp, dan belanjaan pelanggan.",
    answerType: "single_choice",
    options: [
      { id: "CUS-03-0", label: "Tidak menyimpan", score: 0, semanticValue: "level_0" },
      { id: "CUS-03-1", label: "Kontak ada tetapi tercecer", score: 1, semanticValue: "level_1" },
      { id: "CUS-03-2", label: "Ada daftar pelanggan sederhana", score: 2, semanticValue: "level_2" },
      { id: "CUS-03-3", label: "Ada daftar beserta riwayat pembelian", score: 3, semanticValue: "level_3" },
      { id: "CUS-03-4", label: "Data pelanggan dipakai untuk menghubungi kembali atau memberi penawaran", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Data pelanggan belum menjadi aset bisnis yang dapat digunakan untuk meningkatkan repeat order.",
    recommendation: "Buat database pelanggan minimal: nama, kontak, tanggal pembelian, produk, nilai transaksi, status repeat.",
    urgency: 3,
    actionability: 5,
    actionSteps: [
      "Buat satu daftar pelanggan berisi nama, nomor WhatsApp, dan tanggal pembelian.",
      "Isi daftar untuk setiap pembeli baru selama 7 hari tanpa terlewat.",
      "Tambahkan kolom produk yang dibeli dan nilai belanja.",
      "Gunakan daftar tersebut untuk mengirim satu penawaran ke pelanggan lama.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "CUS-04",
    dimensionId: "CUS",
    subdimension: "Kepuasan & Feedback",
    name: "Pengumpulan dan tindak lanjut feedback",
    weightInDimension: 25,
    question: "Kalau pelanggan memberi saran atau komplain, apa yang biasanya Anda lakukan?",
    helperText: "Saran atau komplain bisa datang lewat chat, telepon, atau langsung saat bertemu.",
    answerType: "single_choice",
    options: [
      { id: "CUS-04-0", label: "Tidak ada cara khusus untuk menanganinya", score: 0, semanticValue: "level_0" },
      { id: "CUS-04-1", label: "Menanggapi jika ada komplain", score: 1, semanticValue: "level_1" },
      { id: "CUS-04-2", label: "Kadang mencatat saran/komplain", score: 2, semanticValue: "level_2" },
      { id: "CUS-04-3", label: "Menindaklanjuti dan mencatat masalah yang muncul", score: 3, semanticValue: "level_3" },
      { id: "CUS-04-4", label: "Masalah yang sering muncul dipakai untuk memperbaiki produk atau cara kerja", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha tidak memiliki mekanisme memadai untuk mendeteksi dan memperbaiki masalah pelanggan.",
    recommendation: "Buat mekanisme feedback sederhana dan catat jenis keluhan, penyebab, serta tindak lanjut.",
    urgency: 3,
    actionability: 5,
    actionSteps: [
      "Sediakan satu tempat mencatat saran dan komplain pelanggan (buku atau catatan HP).",
      "Catat setiap saran/komplain selama 2 minggu beserta penyebabnya.",
      "Kelompokkan komplain yang paling sering muncul.",
      "Perbaiki satu penyebab komplain terbanyak dan beri tahu pelanggan yang pernah komplain.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "PRO-01",
    dimensionId: "PRO",
    subdimension: "Value Proposition",
    name: "Kejelasan manfaat dan alasan pelanggan memilih",
    weightInDimension: 25,
    question: "Apakah Anda tahu alasan utama pelanggan memilih produk/jasa Anda dibanding pilihan lain?",
    helperText: "Contoh alasan: rasanya cocok, pengerjaan cepat, bisa dipesan sesuai keinginan.",
    answerType: "single_choice",
    options: [
      { id: "PRO-01-0", label: "Tidak tahu", score: 0, semanticValue: "level_0" },
      { id: "PRO-01-1", label: "Hanya menyebut hal umum seperti 'bagus' atau 'murah'", score: 1, semanticValue: "level_1" },
      { id: "PRO-01-2", label: "Punya 1–2 alasan tetapi masih berdasarkan perkiraan", score: 2, semanticValue: "level_2" },
      { id: "PRO-01-3", label: "Alasan tersebut sering disampaikan oleh pelanggan", score: 3, semanticValue: "level_3" },
      { id: "PRO-01-4", label: "Alasan utama pelanggan dijadikan fokus produk dan promosi", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Produk belum memiliki value proposition yang jelas sehingga mudah masuk perang harga.",
    recommendation: "Rumuskan masalah pelanggan, manfaat utama, dan 1–2 alasan spesifik memilih produk Anda.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Tanyakan pada 10 pelanggan alasan mereka memilih produk/jasa Anda dan catat jawabannya.",
      "Kelompokkan jawaban dan pilih 2 alasan yang paling sering disebut.",
      "Tulis satu kalimat penawaran yang memuat 2 alasan tersebut.",
      "Gunakan kalimat itu di promosi dan catat tanggapan pelanggan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "PRO-02",
    dimensionId: "PRO",
    subdimension: "Kualitas Produk",
    name: "Konsistensi kualitas dan komplain",
    weightInDimension: 30,
    question: "Seberapa sering pelanggan menerima produk/jasa dengan kualitas yang sesuai harapan?",
    helperText: "Sesuai harapan artinya pelanggan menerima yang sesuai dijanjikan, tanpa keluhan berarti.",
    answerType: "single_choice",
    options: [
      { id: "PRO-02-0", label: "Sering ada masalah kualitas", score: 0, semanticValue: "level_0" },
      { id: "PRO-02-1", label: "Cukup sering ada masalah", score: 1, semanticValue: "level_1" },
      { id: "PRO-02-2", label: "Kadang ada masalah", score: 2, semanticValue: "level_2" },
      { id: "PRO-02-3", label: "Hampir selalu sesuai harapan", score: 3, semanticValue: "level_3" },
      { id: "PRO-02-4", label: "Hampir selalu sesuai dan ada cara khusus untuk mengecek kualitas", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Masalah kualitas mengancam kepuasan, repeat order, dan reputasi bisnis.",
    recommendation: "Tetapkan standar mutu untuk produk utama dan checklist quality control sebelum produk diserahkan.",
    urgency: 5,
    actionability: 3,
    actionSteps: [
      "Buat daftar hal yang harus dicek sebelum produk/jasa diserahkan ke pelanggan.",
      "Gunakan daftar cek tersebut untuk semua pesanan selama 7 hari dan catat masalah yang ditemukan.",
      "Cari penyebab masalah yang paling sering terjadi.",
      "Perbaiki penyebab tersebut dan pastikan masalah berkurang minggu ini.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "PRO-03",
    dimensionId: "PRO",
    subdimension: "Portofolio Produk",
    name: "Identifikasi produk unggulan",
    weightInDimension: 20,
    question: "Apakah Anda tahu produk/jasa mana yang perlu difokuskan, diperbaiki, atau dihentikan?",
    helperText: "Maksudnya keputusan produk mana yang diperbanyak dan mana yang dikurangi.",
    answerType: "single_choice",
    options: [
      { id: "PRO-03-0", label: "Tidak tahu", score: 0, semanticValue: "level_0" },
      { id: "PRO-03-1", label: "Hanya berdasarkan feeling", score: 1, semanticValue: "level_1" },
      { id: "PRO-03-2", label: "Melihat penjualan atau masukan pelanggan saja", score: 2, semanticValue: "level_2" },
      { id: "PRO-03-3", label: "Melihat data penjualan dan masukan pelanggan", score: 3, semanticValue: "level_3" },
      { id: "PRO-03-4", label: "Rutin mengevaluasi dan mengubah fokus produk berdasarkan data", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Portofolio produk belum diprioritaskan berdasarkan bukti permintaan dan kontribusi bisnis.",
    recommendation: "Pilih 1–3 produk unggulan berdasarkan volume, omzet, margin, dan repeat purchase.",
    urgency: 2,
    actionability: 4,
    actionSteps: [
      "Kumpulkan data penjualan tiap produk 1 bulan terakhir.",
      "Urutkan produk berdasarkan jumlah penjualan dan tandai yang jarang terjual.",
      "Tanyakan masukan pelanggan tentang produk yang jarang terjual.",
      "Tentukan produk yang difokuskan, diperbaiki, atau dihentikan bulan depan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "PRO-04",
    dimensionId: "PRO",
    subdimension: "Harga & Nilai",
    name: "Dasar penetapan harga",
    weightInDimension: 25,
    question: "Bagaimana Anda menentukan harga jual produk/jasa utama?",
    helperText: "Harga jual produk atau jasa yang paling sering dibeli pelanggan.",
    answerType: "single_choice",
    options: [
      { id: "PRO-04-0", label: "Asal menentukan atau hanya mengikuti harga orang lain", score: 0, semanticValue: "level_0" },
      { id: "PRO-04-1", label: "Berdasarkan perkiraan biaya", score: 1, semanticValue: "level_1" },
      { id: "PRO-04-2", label: "Menghitung biaya utama sebelum menentukan harga", score: 2, semanticValue: "level_2" },
      { id: "PRO-04-3", label: "Menghitung biaya, keuntungan yang diinginkan, dan melihat harga pasar", score: 3, semanticValue: "level_3" },
      { id: "PRO-04-4", label: "Harga ditinjau ulang saat biaya atau kondisi pasar berubah", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Harga tidak memiliki dasar biaya dan nilai yang cukup sehingga berisiko menekan margin.",
    recommendation: "Gunakan HPP + target margin sebagai batas dasar, lalu validasi dengan willingness-to-pay dan kompetitor.",
    urgency: 4,
    actionability: 4,
    actionSteps: [
      "Hitung biaya per satuan untuk 3 produk/jasa utama.",
      "Tentukan keuntungan yang diinginkan per produk lalu hitung harga dasarnya.",
      "Bandingkan harga dasar dengan harga di pasar sekitar.",
      "Tetapkan harga baru untuk minimal satu produk dan catat tanggapan pelanggan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "MKT-01",
    dimensionId: "MKT",
    subdimension: "Target Market",
    name: "Kejelasan sasaran pemasaran",
    weightInDimension: 25,
    question: "Apakah Anda sudah menentukan siapa yang paling ingin dijangkau lewat promosi?",
    helperText: "Contoh kelompok: pelanggan sekitar rumah, pekerja kantor, pembeli oleh-oleh, panitia acara.",
    answerType: "single_choice",
    options: [
      { id: "MKT-01-0", label: "Menargetkan semua orang", score: 0, semanticValue: "level_0" },
      { id: "MKT-01-1", label: "Target masih sangat umum", score: 1, semanticValue: "level_1" },
      { id: "MKT-01-2", label: "Sudah ada kelompok pelanggan tertentu", score: 2, semanticValue: "level_2" },
      { id: "MKT-01-3", label: "Tahu kelompok pelanggan dan apa yang mereka butuhkan", score: 3, semanticValue: "level_3" },
      { id: "MKT-01-4", label: "Cara promosi disesuaikan dengan kelompok pelanggan tersebut", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Pemasaran terlalu luas sehingga pesan, konten, dan biaya berpotensi tidak fokus.",
    recommendation: "Tentukan target utama berdasarkan siapa yang paling membutuhkan, mampu membeli, dan paling mudah dijangkau.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Tulis siapa yang paling butuh produk Anda, mampu membeli, dan paling mudah dijangkau.",
      "Pilih satu kelompok pelanggan sebagai target utama bulan ini.",
      "Buat 3 isi promosi yang khusus berbicara ke kelompok tersebut.",
      "Jalankan promosi ke kelompok itu dan catat berapa yang bertanya atau membeli.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "MKT-02",
    dimensionId: "MKT",
    subdimension: "Konsistensi Aktivitas",
    name: "Frekuensi dan perencanaan pemasaran",
    weightInDimension: 20,
    question: "Dalam 30 hari terakhir, seberapa rutin Anda mempromosikan usaha?",
    helperText: "Promosi termasuk WhatsApp, media sosial, marketplace, brosur, atau menawarkan langsung.",
    answerType: "single_choice",
    options: [
      { id: "MKT-02-0", label: "Tidak melakukan promosi", score: 0, semanticValue: "level_0" },
      { id: "MKT-02-1", label: "Hanya 1–2 kali atau saat sedang sepi", score: 1, semanticValue: "level_1" },
      { id: "MKT-02-2", label: "Beberapa kali tetapi belum rutin", score: 2, semanticValue: "level_2" },
      { id: "MKT-02-3", label: "Rutin setiap minggu", score: 3, semanticValue: "level_3" },
      { id: "MKT-02-4", label: "Rutin sesuai rencana dan dilakukan secara konsisten", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Pemasaran belum cukup konsisten untuk membangun awareness dan aliran calon pelanggan.",
    recommendation: "Buat kalender sederhana 4 minggu dan prioritaskan aktivitas yang terkait langsung dengan target pelanggan.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Buat rencana promosi 4 minggu: apa yang diposting/ditawarkan tiap minggu.",
      "Jalankan promosi minimal 2 kali minggu ini dan catat tanggalnya.",
      "Lanjutkan promosi sesuai rencana dan catat jumlah pertanyaan yang masuk.",
      "Evaluasi rencana 4 minggu dan susun rencana bulan berikutnya.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "MKT-03",
    dimensionId: "MKT",
    subdimension: "Efektivitas Kanal",
    name: "Pengetahuan kanal pemasaran yang menghasilkan prospek/pelanggan",
    weightInDimension: 30,
    question: "Dari cara promosi yang dipakai, apakah Anda tahu mana yang paling banyak mendatangkan calon pembeli atau pembeli?",
    helperText: "Maksudnya cara promosi yang paling banyak membuat orang bertanya atau membeli.",
    answerType: "single_choice",
    options: [
      { id: "MKT-03-0", label: "Tidak tahu", score: 0, semanticValue: "level_0" },
      { id: "MKT-03-1", label: "Hanya berdasarkan perkiraan", score: 1, semanticValue: "level_1" },
      { id: "MKT-03-2", label: "Punya gambaran kasar", score: 2, semanticValue: "level_2" },
      { id: "MKT-03-3", label: "Hasil dari tiap cara promosi dicatat", score: 3, semanticValue: "level_3" },
      { id: "MKT-03-4", label: "Data tersebut dipakai menentukan waktu atau biaya promosi", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha melakukan pemasaran tanpa mengetahui aktivitas mana yang benar-benar menghasilkan pelanggan.",
    recommendation: "Tambahkan pertanyaan 'tahu dari mana' pada transaksi/prospek dan catat hasil tiap kanal.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Selama 7 hari, catat setiap calon pembeli datang dari cara promosi yang mana.",
      "Lanjutkan pencatatan dan jumlahkan calon pembeli per cara promosi.",
      "Bandingkan jumlah calon pembeli dan yang benar-benar membeli dari tiap cara.",
      "Fokuskan waktu dan biaya promosi pada cara yang hasilnya paling baik.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "MKT-04",
    dimensionId: "MKT",
    subdimension: "Pengukuran Hasil",
    name: "Evaluasi biaya dan hasil promosi",
    weightInDimension: 25,
    question: "Setelah membuat promo atau iklan, apa yang biasanya Anda cek untuk melihat hasilnya?",
    helperText: "Cek hasil artinya melihat apa yang terjadi setelah promosi dijalankan.",
    answerType: "single_choice",
    options: [
      { id: "MKT-04-0", label: "Tidak mengecek hasil", score: 0, semanticValue: "level_0" },
      { id: "MKT-04-1", label: "Hanya melihat like, view, atau jumlah pengikut", score: 1, semanticValue: "level_1" },
      { id: "MKT-04-2", label: "Melihat jumlah chat/pertanyaan dari calon pembeli", score: 2, semanticValue: "level_2" },
      { id: "MKT-04-3", label: "Melihat transaksi atau penjualan yang dihasilkan", score: 3, semanticValue: "level_3" },
      { id: "MKT-04-4", label: "Membandingkan biaya promosi dengan transaksi/penjualan yang dihasilkan", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Biaya pemasaran berisiko terbuang karena hasilnya tidak dihubungkan dengan transaksi.",
    recommendation: "Untuk setiap kampanye, catat biaya, jumlah prospek, transaksi, omzet, dan biaya per transaksi.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Untuk promosi yang sedang berjalan, catat biaya yang dikeluarkan.",
      "Catat jumlah pertanyaan dan transaksi yang muncul dari promosi tersebut selama 7 hari.",
      "Hitung biaya promosi dibagi jumlah transaksi yang dihasilkan.",
      "Hentikan atau perbaiki promosi dengan biaya per transaksi paling mahal.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "OPS-01",
    dimensionId: "OPS",
    subdimension: "Proses & SOP",
    name: "Standarisasi proses utama",
    weightInDimension: 20,
    question: "Apakah cara kerja utama usaha sudah punya langkah yang jelas?",
    helperText: "Langkah kerja contohnya: menerima pesanan, menyiapkan, mengecek, menyerahkan ke pelanggan.",
    answerType: "single_choice",
    options: [
      { id: "OPS-01-0", label: "Belum ada cara kerja yang jelas", score: 0, semanticValue: "level_0" },
      { id: "OPS-01-1", label: "Cara kerja hanya diketahui pemilik", score: 1, semanticValue: "level_1" },
      { id: "OPS-01-2", label: "Ada kebiasaan kerja tetapi belum ditulis", score: 2, semanticValue: "level_2" },
      { id: "OPS-01-3", label: "Ada langkah/checklist sederhana yang dipakai", score: 3, semanticValue: "level_3" },
      { id: "OPS-01-4", label: "Langkah kerja dipakai dan diperbaiki jika ada masalah", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Proses sangat bergantung pada kebiasaan individu sehingga hasil sulit konsisten.",
    recommendation: "Dokumentasikan 3 SOP paling kritis: pemrosesan order, produksi/pelayanan, dan quality check.",
    urgency: 3,
    actionability: 4,
    actionSteps: [
      "Tulis langkah kerja utama dari pesanan masuk sampai diterima pelanggan.",
      "Coba jalankan langkah tersebut selama 7 hari dan tandai bagian yang sering tersendat.",
      "Perbaiki satu langkah yang paling sering bermasalah.",
      "Simpan langkah kerja tertulis di tempat yang bisa dilihat orang lain yang membantu usaha.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "OPS-02",
    dimensionId: "OPS",
    subdimension: "Kapasitas",
    name: "Kemampuan memenuhi lonjakan permintaan",
    weightInDimension: 25,
    question: "Kalau pesanan tiba-tiba 2 kali lebih banyak minggu depan, apakah usaha tetap bisa menyelesaikannya tepat waktu dengan kualitas yang sama?",
    helperText: "Pertimbangkan bahan, alat, waktu, dan orang yang tersedia.",
    answerType: "single_choice",
    options: [
      { id: "OPS-02-0", label: "Tidak mampu", score: 0, semanticValue: "level_0" },
      { id: "OPS-02-1", label: "Kemungkinan besar tidak mampu", score: 1, semanticValue: "level_1" },
      { id: "OPS-02-2", label: "Mampu tetapi akan banyak kendala", score: 2, semanticValue: "level_2" },
      { id: "OPS-02-3", label: "Mampu dengan mengatur ulang bahan, waktu, alat, atau tenaga", score: 3, semanticValue: "level_3" },
      { id: "OPS-02-4", label: "Mampu karena kapasitas usaha sudah diketahui dan disiapkan", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Pertumbuhan penjualan dapat memicu keterlambatan atau penurunan kualitas karena kapasitas tidak siap.",
    recommendation: "Hitung kapasitas maksimal per hari/minggu dan identifikasi bottleneck bahan, alat, waktu, atau SDM.",
    urgency: 3,
    actionability: 3,
    actionSteps: [
      "Hitung jumlah maksimal pesanan yang bisa diselesaikan per hari dengan kondisi sekarang.",
      "Tandai bagian yang paling cepat penuh: bahan, alat, waktu, atau tenaga.",
      "Siapkan satu solusi untuk bagian tersebut (tambahan bahan, bantuan tenaga, atau jadwal berbeda).",
      "Uji dengan menerima pesanan lebih banyak satu hari dan catat hasilnya.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "OPS-03",
    dimensionId: "OPS",
    subdimension: "Stok & Supplier",
    name: "Kontrol bahan/stok dan ketahanan pemasok",
    weightInDimension: 20,
    question: "Apakah bahan baku atau stok utama biasanya tersedia saat dibutuhkan?",
    helperText: "Contoh: bahan masakan, kemasan, atau barang dagang yang harus selalu ada.",
    answerType: "single_choice",
    options: [
      { id: "OPS-03-0", label: "Sering habis sehingga pesanan/produksi terganggu", score: 0, semanticValue: "level_0" },
      { id: "OPS-03-1", label: "Kadang habis dan belum ada cara mencegahnya", score: 1, semanticValue: "level_1" },
      { id: "OPS-03-2", label: "Biasanya tersedia tetapi belum ada batas stok minimum", score: 2, semanticValue: "level_2" },
      { id: "OPS-03-3", label: "Ada batas stok minimum dan jadwal pembelian ulang", score: 3, semanticValue: "level_3" },
      { id: "OPS-03-4", label: "Stok dipantau dan ada pemasok/cadangan jika pemasok utama bermasalah", score: 4, semanticValue: "level_4" },
    ],
    applicabilityRule: { all: [{ field: "profile.hasInventory", operator: "equals", value: true }] },
    notApplicableReason: "Tidak relevan untuk model usaha Anda berdasarkan profil yang diisi.",
    allowUserNotApplicable: true,
    diagnosisWhenLow: "Kehabisan stok atau gangguan pemasok dapat langsung menghentikan penjualan/produksi.",
    recommendation: "Tetapkan stok minimum item kritis dan siapkan pemasok alternatif untuk bahan paling penting.",
    urgency: 4,
    actionability: 4,
    actionSteps: [
      "Tulis 5 bahan atau barang paling penting beserta pemakaian per minggu.",
      "Tetapkan batas stok minimum untuk tiap bahan dan tandai kapan harus membeli lagi.",
      "Cari satu pemasok cadangan untuk 2 bahan paling penting.",
      "Cek stok setiap minggu dan pastikan tidak ada yang habis mendadak.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "OPS-04",
    dimensionId: "OPS",
    subdimension: "Quality & Fulfillment",
    name: "Ketepatan waktu dan kualitas pemenuhan order",
    weightInDimension: 20,
    question: "Dalam 1 bulan terakhir, seberapa sering pesanan selesai tepat waktu dan tanpa masalah kualitas?",
    helperText: "Tepat waktu artinya sesuai janji ke pelanggan, tanpa barang cacat atau salah.",
    answerType: "single_choice",
    options: [
      { id: "OPS-04-0", label: "Sering terlambat atau bermasalah", score: 0, semanticValue: "level_0" },
      { id: "OPS-04-1", label: "Cukup sering ada masalah", score: 1, semanticValue: "level_1" },
      { id: "OPS-04-2", label: "Kadang ada masalah", score: 2, semanticValue: "level_2" },
      { id: "OPS-04-3", label: "Hampir semua pesanan tepat waktu dan sesuai", score: 3, semanticValue: "level_3" },
      { id: "OPS-04-4", label: "Kinerja pesanan dicatat dan masalah sangat jarang terjadi", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Masalah fulfillment mengancam kepuasan pelanggan dan repeat purchase.",
    recommendation: "Catat order terlambat/cacat, penyebabnya, dan lakukan perbaikan pada penyebab yang paling sering.",
    urgency: 5,
    actionability: 3,
    actionSteps: [
      "Catat setiap pesanan minggu ini: tepat waktu atau terlambat, ada masalah atau tidak.",
      "Lanjutkan pencatatan dan hitung berapa persen pesanan yang bermasalah.",
      "Cari penyebab keterlambatan atau masalah yang paling sering.",
      "Perbaiki satu penyebab utama dan bandingkan hasilnya dengan minggu sebelumnya.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "OPS-05",
    dimensionId: "OPS",
    subdimension: "Owner Dependency",
    name: "Ketergantungan operasional pada pemilik",
    weightInDimension: 15,
    question: "Kalau Anda sebagai pemilik tidak bisa bekerja selama 3 hari, apa yang terjadi pada usaha?",
    helperText: "Jawab sesuai kondisi sebenarnya, termasuk bila usaha dijalankan sendiri.",
    answerType: "single_choice",
    options: [
      { id: "OPS-05-0", label: "Usaha berhenti", score: 0, semanticValue: "level_0" },
      { id: "OPS-05-1", label: "Hampir semua kegiatan berhenti", score: 1, semanticValue: "level_1" },
      { id: "OPS-05-2", label: "Sebagian kegiatan tetap berjalan", score: 2, semanticValue: "level_2" },
      { id: "OPS-05-3", label: "Sebagian besar kegiatan tetap berjalan", score: 3, semanticValue: "level_3" },
      { id: "OPS-05-4", label: "Usaha tetap berjalan normal karena tugas dan informasi sudah terbagi", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha sangat bergantung pada pemilik dan sulit berkembang tanpa menambah beban owner.",
    recommendation: "Delegasikan satu proses rutin, dokumentasikan SOP, dan pastikan akses informasi tidak hanya dipegang owner.",
    urgency: 3,
    actionability: 3,
    actionSteps: [
      "Tulis pekerjaan yang hanya bisa dikerjakan oleh Anda sendiri.",
      "Pilih satu pekerjaan rutin untuk dialihkan atau dibuat panduan tertulisnya.",
      "Ajari satu orang (pekerja atau keluarga) menjalankan pekerjaan tersebut.",
      "Uji dengan tidak menangani pekerjaan itu selama 3 hari dan catat kendalanya.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "GRW-01",
    dimensionId: "GRW",
    subdimension: "Arah & Rencana Bisnis",
    name: "Target 12 bulan dan monitoring",
    weightInDimension: 30,
    question: "Apakah usaha Anda punya target yang ingin dicapai dalam 12 bulan ke depan?",
    helperText: "Contoh target: menambah pelanggan tetap, membuka cabang, atau menaikkan penjualan.",
    answerType: "single_choice",
    options: [
      { id: "GRW-01-0", label: "Tidak punya target", score: 0, semanticValue: "level_0" },
      { id: "GRW-01-1", label: "Hanya punya keinginan umum", score: 1, semanticValue: "level_1" },
      { id: "GRW-01-2", label: "Punya target angka", score: 2, semanticValue: "level_2" },
      { id: "GRW-01-3", label: "Punya target dan langkah utama untuk mencapainya", score: 3, semanticValue: "level_3" },
      { id: "GRW-01-4", label: "Target rutin dicek dan rencana disesuaikan bila perlu", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha belum memiliki arah yang cukup jelas untuk memprioritaskan penggunaan waktu dan modal.",
    recommendation: "Tetapkan 3–5 target 12 bulan dengan indikator bulanan/kuartalan.",
    urgency: 2,
    actionability: 4,
    actionSteps: [
      "Tulis 3 hal yang ingin dicapai usaha dalam 12 bulan ke depan dalam bentuk angka.",
      "Tentukan langkah utama tiap target dan siapa yang mengerjakan.",
      "Tetapkan penanda kemajuan bulanan untuk tiap target.",
      "Cek kemajuan target bulan ini dan sesuaikan langkah bila perlu.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "GRW-02",
    dimensionId: "GRW",
    subdimension: "Legalitas & Compliance",
    name: "Kesesuaian legalitas dasar usaha",
    weightInDimension: 20,
    question: "Legalitas apa saja yang sudah dimiliki usaha Anda?",
    helperText: "Contoh legalitas: NIB, izin usaha, sertifikat halal, atau izin edar bila memang diperlukan.",
    answerType: "single_choice",
    options: [
      { id: "GRW-02-0", label: "Belum memiliki NIB atau legalitas dasar", score: 0, semanticValue: "level_0" },
      { id: "GRW-02-1", label: "Baru memiliki sebagian legalitas dasar", score: 1, semanticValue: "level_1" },
      { id: "GRW-02-2", label: "Memiliki NIB tetapi izin/sertifikat yang diperlukan belum lengkap", score: 2, semanticValue: "level_2" },
      { id: "GRW-02-3", label: "Mayoritas legalitas yang memang diperlukan sudah lengkap", score: 3, semanticValue: "level_3" },
      { id: "GRW-02-4", label: "Legalitas yang diperlukan lengkap dan masa berlaku/kepatuhannya dipantau", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Kekurangan legalitas dapat membatasi akses pasar, kemitraan, pembiayaan, atau menambah risiko kepatuhan.",
    recommendation: "Petakan legalitas wajib sesuai jenis usaha dan prioritaskan izin yang menjadi syarat pasar/operasional.",
    urgency: 3,
    actionability: 2,
    actionSteps: [
      "Cari tahu legalitas yang memang diperlukan untuk jenis usaha Anda.",
      "Daftarkan atau siapkan berkas untuk legalitas dasar yang belum dimiliki.",
      "Tandai izin atau sertifikat lain yang menjadi syarat pasar yang ingin dimasuki.",
      "Catat masa berlaku setiap legalitas dan jadwalkan pengingat perpanjangan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "GRW-03",
    dimensionId: "GRW",
    subdimension: "Tim, Data & Digital",
    name: "Kemampuan sistem mendukung pertumbuhan",
    weightInDimension: 25,
    question: "Apakah Anda menggunakan catatan penjualan, keuangan, stok, atau pelanggan saat mengambil keputusan usaha?",
    helperText: "Catatan usaha contohnya catatan penjualan, pengeluaran, stok, atau daftar pelanggan.",
    answerType: "single_choice",
    options: [
      { id: "GRW-03-0", label: "Tidak menggunakan catatan/data", score: 0, semanticValue: "level_0" },
      { id: "GRW-03-1", label: "Lebih banyak mengandalkan feeling", score: 1, semanticValue: "level_1" },
      { id: "GRW-03-2", label: "Kadang melihat catatan sebelum mengambil keputusan", score: 2, semanticValue: "level_2" },
      { id: "GRW-03-3", label: "Rutin menggunakan catatan usaha untuk mengambil keputusan", score: 3, semanticValue: "level_3" },
      { id: "GRW-03-4", label: "Rutin membandingkan data dari waktu ke waktu dan memperbaiki strategi", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Fondasi manajemen belum cukup untuk menangani kompleksitas pertumbuhan.",
    recommendation: "Tetapkan pembagian peran dan pilih tools minimum untuk pencatatan penjualan, pelanggan, stok, dan keuangan.",
    urgency: 2,
    actionability: 4,
    actionSteps: [
      "Kumpulkan catatan penjualan, pengeluaran, stok, dan pelanggan dalam satu tempat.",
      "Sebelum mengambil keputusan usaha minggu ini, lihat dulu catatan tersebut dan tulis dasar keputusannya.",
      "Bandingkan catatan bulan ini dengan bulan lalu dan tandai perubahan penting.",
      "Tetapkan jadwal rutin melihat catatan usaha setiap minggu.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
  {
    id: "GRW-04",
    dimensionId: "GRW",
    subdimension: "Resilience & Risk",
    name: "Kesiapan menghadapi gangguan utama",
    weightInDimension: 25,
    question: "Kalau terjadi masalah besar, apakah usaha Anda punya rencana atau pilihan cadangan?",
    helperText: "Contoh masalah besar: pemasok terlambat, alat rusak, penjualan turun, orang penting tidak bisa bekerja.",
    answerType: "single_choice",
    options: [
      { id: "GRW-04-0", label: "Tidak punya", score: 0, semanticValue: "level_0" },
      { id: "GRW-04-1", label: "Biasanya baru mencari solusi saat masalah terjadi", score: 1, semanticValue: "level_1" },
      { id: "GRW-04-2", label: "Punya cadangan untuk satu-dua masalah tertentu", score: 2, semanticValue: "level_2" },
      { id: "GRW-04-3", label: "Sudah tahu risiko utama dan punya pilihan cadangan", score: 3, semanticValue: "level_3" },
      { id: "GRW-04-4", label: "Rencana cadangan sudah disiapkan dan diperiksa kembali secara berkala", score: 4, semanticValue: "level_4" },
    ],
    allowUserNotApplicable: false,
    diagnosisWhenLow: "Usaha sangat rentan terhadap gangguan karena tidak memiliki alternatif atau rencana respons.",
    recommendation: "Identifikasi 5 risiko terbesar, dampak, pencegahan, dan rencana cadangan untuk masing-masing.",
    urgency: 2,
    actionability: 4,
    actionSteps: [
      "Tulis 5 masalah besar yang paling mungkin terjadi pada usaha Anda.",
      "Tentukan dampak tiap masalah dan urutkan yang paling berbahaya.",
      "Siapkan pilihan cadangan untuk 2 masalah teratas (pemasok lain, alat cadangan, bantuan tenaga).",
      "Tulis rencana cadangan tersebut dan tinjau kembali setiap 3 bulan.",
    ],
    isRequired: true,
    version: QUESTIONNAIRE_VERSION,
  },
];

export const CRITICAL_FLAGS: CriticalFlagDef[] = [
  {
    id: "CF-FIN-01",
    code: "CF-FIN-01",
    dimensionId: "FIN",
    name: "Tidak ada pencatatan transaksi",
    severity: "high",
    sourceIndicatorId: "FIN-01",
    triggerExpression: "FIN-01 = 0",
    triggerRule: { all: [{ field: "indicator.FIN-01.score", operator: "equals", value: 0 }] },
    userExplanation: "Tidak tahu kondisi kas/laba secara andal",
    recommendation: "Mulai pencatatan transaksi harian",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-FIN-02",
    code: "CF-FIN-02",
    dimensionId: "FIN",
    name: "Tidak mengetahui HPP",
    severity: "high",
    sourceIndicatorId: "FIN-03",
    triggerExpression: "FIN-03 = 0",
    triggerRule: { all: [{ field: "indicator.FIN-03.score", operator: "equals", value: 0 }] },
    userExplanation: "Harga jual berpotensi tidak menutup biaya",
    recommendation: "Hitung HPP produk utama",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-FIN-03",
    code: "CF-FIN-03",
    dimensionId: "FIN",
    name: "Tidak mengetahui laba/rugi",
    severity: "high",
    sourceIndicatorId: "FIN-04",
    triggerExpression: "FIN-04 = 0",
    triggerRule: { all: [{ field: "indicator.FIN-04.score", operator: "equals", value: 0 }] },
    userExplanation: "Pemilik tidak dapat memastikan usaha menghasilkan keuntungan",
    recommendation: "Buat laporan laba-rugi sederhana",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-FIN-04",
    code: "CF-FIN-04",
    dimensionId: "FIN",
    name: "Tekanan arus kas",
    severity: "critical",
    sourceIndicatorId: "FIN-05",
    triggerExpression: "FIN-05 <= 1",
    triggerRule: { all: [{ field: "indicator.FIN-05.score", operator: "less_or_equal", value: 1 }] },
    userExplanation: "Operasional berpotensi terganggu karena kas tidak cukup",
    recommendation: "Buat cash-flow plan dan kendalikan biaya",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-FIN-05",
    code: "CF-FIN-05",
    dimensionId: "FIN",
    name: "Cadangan kas sangat rendah/tidak diketahui",
    severity: "high",
    sourceIndicatorId: "FIN-06",
    triggerExpression: "FIN-06 = 0",
    triggerRule: { all: [{ field: "indicator.FIN-06.score", operator: "equals", value: 0 }] },
    userExplanation: "Usaha rentan terhadap penurunan penjualan atau kejadian tak terduga",
    recommendation: "Bangun buffer kas bertahap",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-SAL-01",
    code: "CF-SAL-01",
    dimensionId: "SAL",
    name: "Penurunan penjualan tajam",
    severity: "high",
    sourceIndicatorId: "SAL-01",
    triggerExpression: "SAL-01 = 0",
    triggerRule: { all: [{ field: "indicator.SAL-01.score", operator: "equals", value: 0 }] },
    userExplanation: "Permintaan/transaksi menurun signifikan",
    recommendation: "Analisis produk, pelanggan, dan kanal penyebab penurunan",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-SAL-02",
    code: "CF-SAL-02",
    dimensionId: "SAL",
    name: "Tidak tahu sumber pendapatan utama",
    severity: "medium",
    sourceIndicatorId: "SAL-03",
    triggerExpression: "SAL-03 = 0",
    triggerRule: { all: [{ field: "indicator.SAL-03.score", operator: "equals", value: 0 }] },
    userExplanation: "Fokus bisnis berisiko salah sasaran",
    recommendation: "Analisis kontribusi omzet dan margin per produk",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-CUS-01",
    code: "CF-CUS-01",
    dimensionId: "CUS",
    name: "Tidak tahu pelanggan utama",
    severity: "medium",
    sourceIndicatorId: "CUS-01",
    triggerExpression: "CUS-01 = 0",
    triggerRule: { all: [{ field: "indicator.CUS-01.score", operator: "equals", value: 0 }] },
    userExplanation: "Produk dan pemasaran tidak memiliki sasaran yang jelas",
    recommendation: "Petakan segmen pelanggan utama",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-CUS-02",
    code: "CF-CUS-02",
    dimensionId: "CUS",
    name: "Repeat purchase sangat rendah",
    severity: "high",
    sourceIndicatorId: "CUS-02",
    triggerExpression: "CUS-02 = 1",
    triggerRule: { all: [{ field: "indicator.CUS-02.score", operator: "equals", value: 1 }, { field: "profile.repeatPurchaseApplicable", operator: "equals", value: true }] },
    userExplanation: "Ketergantungan tinggi pada akuisisi pelanggan baru",
    recommendation: "Bangun follow-up dan strategi repeat order",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-PRO-01",
    code: "CF-PRO-01",
    dimensionId: "PRO",
    name: "Value proposition tidak jelas",
    severity: "medium",
    sourceIndicatorId: "PRO-01",
    triggerExpression: "PRO-01 = 0",
    triggerRule: { all: [{ field: "indicator.PRO-01.score", operator: "equals", value: 0 }] },
    userExplanation: "Produk mudah masuk perang harga",
    recommendation: "Rumuskan manfaat dan pembeda spesifik",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-PRO-02",
    code: "CF-PRO-02",
    dimensionId: "PRO",
    name: "Masalah kualitas berulang",
    severity: "critical",
    sourceIndicatorId: "PRO-02",
    triggerExpression: "PRO-02 <= 1",
    triggerRule: { all: [{ field: "indicator.PRO-02.score", operator: "less_or_equal", value: 1 }] },
    userExplanation: "Risiko kehilangan pelanggan dan reputasi",
    recommendation: "Terapkan standar mutu dan QC",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-PRO-03",
    code: "CF-PRO-03",
    dimensionId: "PRO",
    name: "Harga tanpa dasar biaya/nilai",
    severity: "high",
    sourceIndicatorId: "PRO-04",
    triggerExpression: "PRO-04 = 0",
    triggerRule: { all: [{ field: "indicator.PRO-04.score", operator: "equals", value: 0 }] },
    userExplanation: "Margin dapat tergerus",
    recommendation: "Perbaiki HPP dan metode pricing",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-MKT-01",
    code: "CF-MKT-01",
    dimensionId: "MKT",
    name: "Target market tidak jelas",
    severity: "medium",
    sourceIndicatorId: "MKT-01",
    triggerExpression: "MKT-01 = 0",
    triggerRule: { all: [{ field: "indicator.MKT-01.score", operator: "equals", value: 0 }] },
    userExplanation: "Aktivitas marketing tidak fokus",
    recommendation: "Tentukan target utama",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-MKT-02",
    code: "CF-MKT-02",
    dimensionId: "MKT",
    name: "Beriklan tanpa pengukuran hasil",
    severity: "high",
    sourceIndicatorId: "MKT-04",
    triggerExpression: "MKT-04 = 0 + ada paid ads",
    triggerRule: { all: [{ field: "indicator.MKT-04.score", operator: "equals", value: 0 }, { field: "profile.usesPaidAds", operator: "equals", value: true }] },
    userExplanation: "Anggaran marketing berisiko terbuang",
    recommendation: "Ukur leads, transaksi, omzet dan biaya per transaksi",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-OPS-01",
    code: "CF-OPS-01",
    dimensionId: "OPS",
    name: "Tidak mampu menangani 2x order",
    severity: "high",
    sourceIndicatorId: "OPS-02",
    triggerExpression: "OPS-02 <= 1 + tren tumbuh",
    triggerRule: { all: [{ field: "indicator.OPS-02.score", operator: "less_or_equal", value: 1 }, { field: "indicator.SAL-01.score", operator: "greater_or_equal", value: 3 }] },
    userExplanation: "Pertumbuhan dapat merusak kualitas/layanan",
    recommendation: "Hitung kapasitas dan bottleneck",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-OPS-02",
    code: "CF-OPS-02",
    dimensionId: "OPS",
    name: "Kehabisan stok/gangguan supplier berulang",
    severity: "high",
    sourceIndicatorId: "OPS-03",
    triggerExpression: "OPS-03 = 0",
    triggerRule: { all: [{ field: "indicator.OPS-03.score", operator: "equals", value: 0 }, { field: "indicator.OPS-03.applicable", operator: "equals", value: true }] },
    userExplanation: "Produksi/penjualan dapat berhenti",
    recommendation: "Terapkan minimum stock dan supplier alternatif",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-OPS-03",
    code: "CF-OPS-03",
    dimensionId: "OPS",
    name: "Fulfillment buruk",
    severity: "critical",
    sourceIndicatorId: "OPS-04",
    triggerExpression: "OPS-04 <= 1",
    triggerRule: { all: [{ field: "indicator.OPS-04.score", operator: "less_or_equal", value: 1 }] },
    userExplanation: "Risiko komplain dan kehilangan repeat order",
    recommendation: "Analisis keterlambatan/cacat dan perbaiki penyebab",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-OPS-04",
    code: "CF-OPS-04",
    dimensionId: "OPS",
    name: "Owner dependency sangat tinggi",
    severity: "high",
    sourceIndicatorId: "OPS-05",
    triggerExpression: "OPS-05 <= 1",
    triggerRule: { all: [{ field: "indicator.OPS-05.score", operator: "less_or_equal", value: 1 }, { any: [{ field: "profile.employeeCount", operator: "greater_than", value: 1 }, { field: "profile.stage", operator: "in", value: ["bertumbuh", "berkembang", "scale_up"] }] }] },
    userExplanation: "Bisnis sulit berkembang dan rentan saat owner tidak tersedia",
    recommendation: "Delegasi dan dokumentasi SOP",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-GRW-01",
    code: "CF-GRW-01",
    dimensionId: "GRW",
    name: "Legalitas dasar belum tersedia",
    severity: "high",
    sourceIndicatorId: "GRW-02",
    triggerExpression: "GRW-02 = 0",
    triggerRule: { all: [{ field: "indicator.GRW-02.score", operator: "equals", value: 0 }, { field: "profile.operatingYears", operator: "greater_or_equal", value: 1 }] },
    userExplanation: "Akses pasar/kemitraan/pembiayaan dapat terbatas",
    recommendation: "Lengkapi legalitas relevan",
    active: true,
    version: SCORING_VERSION,
  },
  {
    id: "CF-GRW-02",
    code: "CF-GRW-02",
    dimensionId: "GRW",
    name: "Tidak ada mitigasi risiko",
    severity: "high",
    sourceIndicatorId: "GRW-04",
    triggerExpression: "GRW-04 = 0",
    triggerRule: { all: [{ field: "indicator.GRW-04.score", operator: "equals", value: 0 }] },
    userExplanation: "Usaha rentan terhadap gangguan utama",
    recommendation: "Buat risk register dan contingency plan",
    active: true,
    version: SCORING_VERSION,
  },
];

export const HEALTH_STATUS_RULES: HealthStatusRule[] = [
  { id: "kritis", min: 0, max: 39, label: "Kritis", tone: "critical", summary: "Banyak bagian dasar usaha belum tersedia. Fokus pada perbaikan pondasi." },
  { id: "rentan", min: 40, max: 54, label: "Rentan", tone: "warning", summary: "Usaha berjalan, tetapi beberapa bagian penting masih mudah goyah." },
  { id: "cukup_sehat", min: 55, max: 69, label: "Cukup Sehat", tone: "fair", summary: "Pondasi usaha mulai terbentuk. Beberapa bagian masih perlu diperkuat." },
  { id: "sehat", min: 70, max: 84, label: "Sehat", tone: "healthy", summary: "Sebagian besar bagian usaha sudah berjalan baik dan terkelola." },
  { id: "sangat_sehat", min: 85, max: 100, label: "Sangat Sehat", tone: "excellent", summary: "Usaha dikelola dengan rapi dan keputusan sudah berbasis catatan." },
];

export const CROSS_DIMENSION_RULES: CrossDimensionRule[] = [
  {
    id: "CD-01",
    conditions: [
      { dimensionId: "MKT", operator: "greater_or_equal", value: 70 },
      { dimensionId: "SAL", operator: "greater_or_equal", value: 70 },
      { dimensionId: "FIN", operator: "less_than", value: 55 },
    ],
    statement:
      "Aktivitas pemasaran dan penjualan sudah menghasilkan transaksi, tetapi hasil tersebut belum berubah menjadi kondisi keuangan yang kuat.",
    possibleCauseIndicatorIds: ["FIN-03", "FIN-04", "FIN-05", "FIN-02"],
  },
  {
    id: "CD-02",
    conditions: [
      { dimensionId: "PRO", operator: "greater_or_equal", value: 70 },
      { dimensionId: "MKT", operator: "less_than", value: 55 },
    ],
    statement:
      "Produk menunjukkan pondasi yang cukup baik, tetapi kemampuan menjangkau calon pembeli masih membatasi pertumbuhan.",
    possibleCauseIndicatorIds: ["MKT-01", "MKT-02", "MKT-03"],
  },
  {
    id: "CD-03",
    conditions: [
      { dimensionId: "SAL", operator: "greater_or_equal", value: 70 },
      { dimensionId: "OPS", operator: "less_than", value: 55 },
    ],
    statement:
      "Permintaan lebih kuat daripada kesiapan operasional. Pertumbuhan dapat memicu keterlambatan, kehabisan stok, atau masalah kualitas.",
    possibleCauseIndicatorIds: ["OPS-02", "OPS-03", "OPS-04"],
  },
  {
    id: "CD-04",
    conditions: [
      { dimensionId: "MKT", operator: "greater_or_equal", value: 70 },
      { dimensionId: "SAL", operator: "less_than", value: 55 },
    ],
    statement:
      "Promosi belum cukup berubah menjadi transaksi. Periksa kembali target pembeli, penawaran, dan cara pembeli menyelesaikan pembelian.",
    possibleCauseIndicatorIds: ["SAL-02", "SAL-03", "SAL-04", "CUS-01"],
  },
];

export const FIN06_SEMANTIC_DIAGNOSIS: Record<string, string> = {
  unknown:
    "Usaha belum mengetahui berapa lama uang usaha bisa bertahan. Ini persoalan catatan dan perencanaan, bukan berarti kas pasti menipis.",
  less_than_2_weeks:
    "Uang usaha diperkirakan hanya cukup untuk kurang dari 2 minggu. Ini risiko kas jangka pendek yang perlu ditangani segera.",
};
