/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AssessmentAssessmentIdRouteImport } from './routes/assessment.$assessmentId'
import { Route as AssessmentStartRouteImport } from './routes/assessment.start'
import { Route as ResultsAssessmentIdRouteImport } from './routes/results.$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AssessmentAssessmentIdRoute = AssessmentAssessmentIdRouteImport.update({
  id: '/assessment/$assessmentId',
  path: '/assessment/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentStartRoute = AssessmentStartRouteImport.update({
  id: '/assessment/start',
  path: '/assessment/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAssessmentIdRoute = ResultsAssessmentIdRouteImport.update({
  id: '/results/$assessmentId',
  path: '/results/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/results/$assessmentId': typeof ResultsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/results/$assessmentId': typeof ResultsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/results/$assessmentId': typeof ResultsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/tentang'
    | '/dashboard'
    | '/assessment/$assessmentId'
    | '/assessment/start'
    | '/results/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/tentang'
    | '/dashboard'
    | '/assessment/$assessmentId'
    | '/assessment/start'
    | '/results/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/tentang'
    | '/_authenticated/dashboard'
    | '/assessment/$assessmentId'
    | '/assessment/start'
    | '/results/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TentangRoute: typeof TentangRoute
  AssessmentAssessmentIdRoute: typeof AssessmentAssessmentIdRoute
  AssessmentStartRoute: typeof AssessmentStartRoute
  ResultsAssessmentIdRoute: typeof ResultsAssessmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/assessment/$assessmentId': {
      id: '/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/assessment/$assessmentId'
      preLoaderRoute: typeof AssessmentAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/start': {
      id: '/assessment/start'
      path: '/assessment/start'
      fullPath: '/assessment/start'
      preLoaderRoute: typeof AssessmentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$assessmentId': {
      id: '/results/$assessmentId'
      path: '/results/$assessmentId'
      fullPath: '/results/$assessmentId'
      preLoaderRoute: typeof ResultsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TentangRoute: TentangRoute,
  AssessmentAssessmentIdRoute: AssessmentAssessmentIdRoute,
  AssessmentStartRoute: AssessmentStartRoute,
  ResultsAssessmentIdRoute: ResultsAssessmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
