/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AssessmentAssessmentIdRouteImport } from './routes/assessment.$assessmentId'
import { Route as AssessmentStartRouteImport } from './routes/assessment.start'
import { Route as ResultsAssessmentIdRouteImport } from './routes/results.$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentAssessmentIdRoute = AssessmentAssessmentIdRouteImport.update({
  id: '/assessment/$assessmentId',
  path: '/assessment/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentStartRoute = AssessmentStartRouteImport.update({
  id: '/assessment/start',
  path: '/assessment/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAssessmentIdRoute = ResultsAssessmentIdRouteImport.update({
  id: '/results/$assessmentId',
  path: '/results/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tentang': typeof TentangRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/results/$assessmentId': typeof ResultsAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tentang': typeof TentangRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/results/$assessmentId': typeof ResultsAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/tentang': typeof TentangRoute
  '/assessment/$assessmentId': typeof AssessmentAssessmentIdRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/results/$assessmentId': typeof ResultsAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/tentang'
    | '/assessment/$assessmentId'
    | '/assessment/start'
    | '/results/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/tentang'
    | '/assessment/$assessmentId'
    | '/assessment/start'
    | '/results/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/tentang'
    | '/assessment/$assessmentId'
    | '/assessment/start'
    | '/results/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  TentangRoute: typeof TentangRoute
  AssessmentAssessmentIdRoute: typeof AssessmentAssessmentIdRoute
  AssessmentStartRoute: typeof AssessmentStartRoute
  ResultsAssessmentIdRoute: typeof ResultsAssessmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$assessmentId': {
      id: '/assessment/$assessmentId'
      path: '/assessment/$assessmentId'
      fullPath: '/assessment/$assessmentId'
      preLoaderRoute: typeof AssessmentAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/start': {
      id: '/assessment/start'
      path: '/assessment/start'
      fullPath: '/assessment/start'
      preLoaderRoute: typeof AssessmentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$assessmentId': {
      id: '/results/$assessmentId'
      path: '/results/$assessmentId'
      fullPath: '/results/$assessmentId'
      preLoaderRoute: typeof ResultsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  TentangRoute: TentangRoute,
  AssessmentAssessmentIdRoute: AssessmentAssessmentIdRoute,
  AssessmentStartRoute: AssessmentStartRoute,
  ResultsAssessmentIdRoute: ResultsAssessmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
